[project]
name = "iot"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "eclipse-sumo>=1.23.1",
    "libsumo>=1.23.1",
    "sumolib>=1.23.1",
    "traci>=1.22.0",
]
